### ISSUE TITLE
A Taste of Dotty

### ISSUE THREAD

**Issue by hermannhueck** [scala-berlin/scala-berlin#10]
Hi Scalaties, On _April 28th 2021_ _Hermann_  will give a feature overview of Dotty/Scala 3.
_location: online_ 

# Talk

#### Ready by: &nbsp; March 31st 2021

<br/>

## A Taste of Dotty

<br/>

## Abstract
This presentation is an introduction to Dotty / Scala 3 and an overview of many features.
It covers those features which I deem most important for Scala application developers.
For detailed information see the [Dotty documentation](https://dotty.epfl.ch/docs/index.html).

#### Dotty Features to Cover
- Top Level _def_'s and _val_'s
- Indentation / Optional Braces
- New Control Syntax
- Main Methods
- Constructor invocations w/o _new_
- Enums and ADTs
- Opaque Type Aliases
- Extension Methods
- Givens - The new Implicits
- Typeclasses
- Type Lambdas
- Intersection Types
- Union Types
- Explicit Nulls
- Strict/Multiversial Equality
- and more ...

<br/>

# About the speaker:
Hermann Hueck is a freelance Functional Scala Developer,
currently doing personal research on advanced Scala topics
like shapeless, ZIO, the cats eco system, Dotty, etc.
More info about me in my XING profile.

### Links to speaker
https://www.xing.com/profile/Hermann_Hueck/

<br/>

# Schedule
- 18:30 - 19:00 Get-together, with food & drinks
- 19:00 - 19:05 Short intro
- 19:05 - 19:45 Talk
- 19:45 - Networking with drinks (not sponsored ;)

# Technicalities
- _How to get to the meetup_
- _Accessibility: The meeting space is accessible via zoom._
- The talk will be in English and will not get recorded.

**Comment by markusjura** [comment]
Hi @hermannhueck, Scala 3 is around the corner. So it is great timing for this talk. Are you still interested in giving this talk at an upcoming meetup?

We are also planning a 3 hours "Scala 3" workshop so I think it would be great if we present this session at the meetup and the workshop in a similar timeframe so that community getting support and motivated to start with Scala 3.

**Comment by hermannhueck** [comment]
Hi @markusjura,

Thanks, for the offer. And yes, I am still interested in giving the talk.

As more than a year has passed since I made the proposal I might think about changing some things.
As coding might more adequate for the 3 hours workshop you also announced,
it might be better to give my talk in the format of a traditional presentation.
I also might change the content of the talk a bit compared to what I announced.

I think it might be better that I give my talk at a date before the workshop.
Thus my talk could give a Scala 3 overview and show more features and the workshop could give
more detailed knowledge and practical introduction about fewer specific features.

**Comment by markusjura** [comment]
Hi @hermannhueck,

your suggestion sounds perfect. Does 28.04., Wednesday, work for you? We would have then the following upcoming talks:

- 14.04: Sinisa: [Concurrency with Fibers in Scala](https://www.meetup.com/Scala-Berlin-Brandenburg/events/277152720)
- 28.04: Hermann: Scala 3 Overview (title tbd)
- 01.05: Bartek: [Scala 3 Crash Course](https://github.com/scala-berlin/scala-berlin/issues/13)

Would be great if you could update your talk abstract accordingly. Let me know if it is done. I'll then create the event on meetup.com

Do you want to host your meetup event or should we as MOIA do it (via Zoom)?

**Comment by hermannhueck** [comment]
Hi @markusjura,

28.04 fits very well. I reserved the date for the talk.

I would prefer that you as MOIA host the talk.

And yes, I will update the abstract. I already planned to do that. When done I will notify you.
The new title will be: A Taste of Dotty

**Comment by hermannhueck** [comment]
Hi @markusjura,

I updated the abstract of the talk.
Talk can be scheduled.

**Comment by markusjura** [comment]
Perfect. I'll schedule the event on meetup.com today.

**Comment by markusjura** [comment]
Scheduled via meetup.com: https://www.meetup.com/Scala-Berlin-Brandenburg/events/277396184/
