### ISSUE TITLE
Concurrency with Fibers in Scala

### ISSUE THREAD

**Issue by slouc** [scala-berlin/scala-berlin#12]
**Talk**

"Concurrency with Fibers in Scala"

**Abstract**

Official abstract for the talk:

> Modern CPUs and operating systems are based on concurrent execution, designed around the threading model. In order to make their life easier, software engineers have come up with the concept of green threads which operate on a higher layer of abstraction, and fibers are one popular implementation of that idea.
> 
> In this talk, I will explain the basics of the fiber model and demonstrate them in practice using modern Scala libraries (Cats Effect and ZIO).

For those who are reading this, here's a quick summary of the covered topics:

- Main principles of thread-based concurrency
- What's a fiber, relationship between threads and fibers
- Preemptive vs cooperative scheduling
- Asynchronous boundary
- Continuations and run loop
- Fairness vs throughput
- Examples using Cats-Effect and ZIO

**About the speaker**

Sinisa is a software engineer and functional programming enthusiast with a decade of experience in implementing backend systems across various domains, from telecom and e-commerce to fintech. He is currently helping shape the future of mobility at MOIA.

**Notes**

This is an entry-level talk about general principles behind fibers. The idea is to first explain the theory, and then demonstrate it on minimal, but complete examples. Examples are not pseudocode, incomplete snippets or real life code with extra dependencies; they are self-sufficient programs with 15-20 LOC ready to be run with only Scala and Cats Effect / ZIO dependencies.

**Comment by slouc** [comment]
Since the differences between CE and ZIO are so minor, I will be dropping the CE from the title. Examples will be following CE3 syntax simply to stick to one consistent style, but I will show the corresponding ZIO examples in the end, demonstrating how the code for these particular examples stays almost identical (because the talk is based on core principles common to both libraries).

**Comment by markusjura** [comment]
Planned on 14.04.2021: https://www.meetup.com/Scala-Berlin-Brandenburg/events/277152720
