### ISSUE TITLE
Scala 3 Crash Course

### ISSUE THREAD

**Issue by bszwej** [scala-berlin/scala-berlin#13]
**Workshop**

Scala 3 Crash Course

**Abstract**

Scala 3 RC2 is already here and we can expect the final release soon (maybe it's already here as you're reading this)! That's why it's a good timing for playing around and seeing what's there. In this workshop, we'll explore hands-on the most important features and learn:
- How to use the new braceless syntax.
- How to use enums to model simple enumerations as well as complex ADTs.
- How to use contextual abstractions (givens, extension methods, type classes, conversions, context functions, new import syntax) and why they're awesome.
- How opaque types replace and deprecate value classes and why they're better.
- How union and intersection types nicely enrich the type system.

The goal is to equip you with practical skills that will allow you to start or migrate your project(s) to Scala 3. That's why during the workshop you will be solving exercises i.e. refactoring the code from Scala 2 to Scala 3 using the new shiny constructs.

This workshop is dedicated to Scala 2 developers and assumes prior knowledge about implicits, ADTs, and type classes. No knowledge of Scala 3 is required.

**Duration**
3 hours

**Prerequisites**
Please checkout [this repository](https://github.com/bszwej/scala-3-crash-course) and make sure you can import it in your favorite IDE & compile. I'll be using VScode + metals and encourage you to do the same. Intellij should be fine as well.  Should you have any questions, give me a shout on Twitter (@bszwej).

**About the speaker**
Bartek is a software engineer, who is a big fan of Scala (since 2.11.x) and functional programming. He's been mostly doing backend (and a bit of data) engineering across multiple domains like e-commerce, logistics, or payments at different companies over the years. He's currently working in the Payments team at MOIA.

**Comment by markusjura** [comment]
Scheduled on meetup.com: https://www.meetup.com/Scala-Berlin-Brandenburg/events/277396170/
