### ISSUE TITLE
Scala on GraalVM and AWS Lambda

### ISSUE THREAD

**Issue by Jentsch** [scala-berlin/scala-berlin#2]

**Comment by Jentsch** [comment]
@markusjura

**Comment by markusjura** [comment]
@Jentsch Based on the conversation in https://github.com/scala-berlin/scala-berlin/issues/4#issuecomment-530687410, should I do the talk in November? What about 12.11.?

**Comment by Jentsch** [comment]
12.11. is fine. Thanks in advance for your talk

**Comment by markusjura** [comment]
Cool, 12.11 it is then. We will host the event at MOIA.

**Comment by markusjura** [comment]
The talk was originally planned for December 2019 but unfortunately, I don't have the time to prepare it. If there is a large interest in this topic, I am happy to share insights about this topic in 2020.
