### ISSUE TITLE
Enable Simon Hafner to present tutorial on Fold / Unfold

### ISSUE THREAD

**Issue by ppurang** [scala-berlin/scala-berlin#3]
Simon Hafner (https://github.com/reactormonk) contacted me with this request: 

"I'll be giving a tutorial on Fold / Unfold in Scala at ICFP in three weeks and I wanted to know if it would be possible to test run it at the Scala meetup this or next week."

I know it is short notice, but we should try and enable this wish.

@Jentsch could you maybe postpone Kata?

**Comment by reactormonk** [comment]
Here's my abstract. The fold part will probably be 1:15, the unfold maybe as long, maybe less.

> With a fold, you can describe how to transforming a data structure with multiple elements into a single one. An example would be the sum of numbers in an array. However, working with the more well-known versions of fold, foldRight/reduceRight/etc. is complicated because you usually have two running variables at a time. This workshop explains patterns to make writing folds easier.
> 
> Unfolds are the opposite, in math speak the dual, of folds. They construct a data structure from a single element. This pattern is a bit less-known, as it occurs a bit less frequently than folds. A prime example would be to abstract over pagination from an external source, and transform the input into a continuous data structure.

**Comment by Jentsch** [comment]
Sure I can postpone the Kata Session. Do you already have a location?

**Comment by reactormonk** [comment]
I could ask around, but if you'd have something that'd be great. My past workshops have been 12 people per instructor, I could probably find a secondary person, so we'd need space for 24 people (with laptops).

**Comment by Jentsch** [comment]
We have the meetup next week, 13. and 15 here in the Leanovate office. This week isn't possible for us. We would be fine with either 12 and 24 people.

If you looking for a secondary person, I could help. (depends a bit on how much preparation is needed)

**Comment by reactormonk** [comment]
So 13. or 15. work, or they don't work? In case of a) they work, I'll take 13. Otherwise 16.

**Comment by Jentsch** [comment]
Sorry for my inaccurate language. I meant 13. and 15. are free. So we will have the meetup next Tuesday.

Do I understand you correctly, that the hole workshop will take around 2,5 hours? (Including breaks)

**Comment by ppurang** [comment]
Tuesday, darn, can't make it .. but the next week is anyways loaded. Thanks, Daniel for jumping on it :)

**Comment by reactormonk** [comment]
With breaks, I'd say 2.5-3h.

**Comment by Jentsch** [comment]
Ok, then doors open at 18:00. Workshop starts at 18:30. Short break around 20:00. Official end somewhere between 21:00 and 21:30. `sudo rm /people/* -rf` around 22:00.

Anything to say about your tutorial/workshop style? Do you need a beamer?

I'll announce the Meetup today for 12 people. We can update the details, when they come clear.

**Comment by reactormonk** [comment]
Yeah, a projector would be helpful. I usually do 1/3 talking, 2/3 letting people code. For the 2/3 part I'd require more teachers - usually just helping out solving the exercises. Hence more people required if we wanna scale.

**Comment by Jentsch** [comment]
I published the event: https://www.meetup.com/de-DE/Scala-Berlin-Brandenburg/events/263784386/ You should be able to edit it, if you want to.

**Comment by reactormonk** [comment]
Sweet, thanks!

**Comment by ppurang** [comment]
@Jentsch we need to manage the no shows more aggressively as the seats are limited and hence very precious. I recommend sending an email out a day/two days before the event to ask people to review their RSVPs and point out the severe restrictions on numbers and hence the need to allow others, who can indeed participate. 

Could we record parts of it? Or send out Github repo for others to try stuff up?

**Comment by Jentsch** [comment]
I thought the same. I will send a reminder to review the RSVP and to bring a laptop on Saturday.

To reduce the pressure we could add more seats. @reactormonk I could assist you during the coding part, if you like.

Regarding the recording: it's a long ständig request of the some people. We have the equipment here. @reactormonk would you be ok with recording your session?

**Comment by reactormonk** [comment]
I asked @jcranky, he agreed to help out. So I increased the number to 24.

I don't think the record is gonna help a whole lot TBH.

**Comment by ppurang** [comment]
Nice! :clap:

**Comment by reactormonk** [comment]
I suppose based on the waitlist there's some interest. We/I should probably send out an email asking people to double-check if they wanna come or not. Do y'all think that way we can get below 24 students or should I word the mail a bit harsher?

**Comment by Jentsch** [comment]
I don't think we get below 24 people. I would mention I the mail, that the space is limited and if anybody is nur sure he/she should allow someone else to participate.

I would also mention that everybody has to bring a laptop.

**Comment by Jentsch** [comment]
Something along the lines of

Hi Scalaties,

we are all looking forward to learn about the dualism of fold and unfold this Tuesday. But you can have a tutorial for a limited amount of participants and there some people on the waiting list, that would love to attend too.

So please check your response and if your plans changed since your initial yes response, allow some else to get your seat.

Also quick reminder, please bring your laptop.

**Comment by Jentsch** [comment]
Sent the message

**Comment by ppurang** [comment]
And how was it? Summary would be great, if anything could be learnt from this meetup. Thanks again @Jentsch and @reactormonk

**Comment by reactormonk** [comment]
I've got my list of feedback, but that's mostly personal and/or for the presentation.

**Comment by ppurang** [comment]
Sure. Having a dry run was an excellent idea. The feedback can only make the real event better. I was just wondering if there are takeaways that might apply to other such workshops in general.

**Comment by Jentsch** [comment]
We had a good show rate of 75%. We can improve in communicating the expected level of the workshop. Simon was very good in adapting on the fly and most people where able to do the last exercise. But expectation management seems to be a good idea.
In general I think doing more practical things is a good idea.

I should improve the grammar of the reminder mail and how to introduce the talk during the event.
