### ISSUE TITLE
ZIO STM

### ISSUE THREAD

**Issue by Jentsch** [scala-berlin/scala-berlin#5]

**Comment by mijicd** [comment]
As already discussed, I'd like to present this topic. My idea is to cover the following aspects:

- ZIO concurrency primitives
- brief overview of STMs
- ZIO STM design
- examples

I could adjust the content depending on the talk duration and audience.

**Comment by Jentsch** [comment]
Right now this proposed talk is planned to take place around the same time as #4. Can we resolve this?

**Comment by markusjura** [comment]
John De Goes will talk about ZIO on the 1st of Nov at The Hub (Zalando). We will cross-promote this event.

Therefore, I'd suggest postponing this the ZIO STM talk to November and https://github.com/scala-berlin/scala-berlin/issues/2 to December. 

@mijicd Does it work for you and which date in November between week 2-4 would suit you best?

The talk https://github.com/scala-berlin/scala-berlin/issues/4 was planned for December but we did not get a final response by the speaker @reactormonk yet. So finding a date for this event is still open.

**Comment by mijicd** [comment]
@markusjura just checked my calendar, in November I'm available at any date after 18th.

**Comment by Jentsch** [comment]
I'll create a doodle and send it to mijicd and our office.

**Comment by markusjura** [comment]
@mijicd In the meantime, can you send an abstract of the talk and a brief bio of yourself so that we can prepare the meetup.com event?

@Jentsch This talk will be hosted by your company?

**Comment by mijicd** [comment]
@markusjura I'll send these by the end of the week.
