### ISSUE TITLE
Deploying Spark apps on Kubernetes talk 2019-10-09

### ISSUE THREAD

**Issue by roksolana-d** [scala-berlin/scala-berlin#7]
I am a member of Scala Kyiv User group but I will be visiting Berlin in 9-12th of October. If there is a possibility to organise the meetup in this time period I would like to present a topic "Fuck-ups story of lighting a spark in the Kubernetes sea".
I have more concise version of this talk for 30 minutes and an extended one for 40 minutes.

**Abstract**
Big data, Spark, Kubernetes - you may have heard these buzzwords far too many times. Have you ever thought of combining all of them? Running spark jobs on Kubernetes - sounds intriguing! But sailing the unknown see always goes with a challenge, and not even one. And who knows what is hiding deep in the water? If you are ready, let’s embark on this dangerous yet exciting journey.

**Description**
In this talk, I am going to talk about new Spark operator for Kubernetes which allows to run Spark jobs on Kubernetes in a more automated way. The audience will find out about all the challenges my team and I encountered while researching this possibility. How we came all the way through using Spark operator alpha version which then got updated to beta (you know, updates). How we dealt with problems and challenges we encountered on our way.

**Comment by Jentsch** [comment]
I'm on vacation during this time. markusjura can you handle this?

**Comment by roksolana-d** [comment]
@markusjura  I believe, the tag did not work :)

**Comment by Jentsch** [comment]
Thanks

**Comment by markusjura** [comment]
Yes, sure. Out of 09.10 - 12.10, the 09.10. would work best for me.

@Jentsch When do want to schedule https://github.com/scala-berlin/scala-berlin/issues/5 and does it conflict with this talk here?

If it all works out timewise, we are happy to host the "Deploying Sparks apps on Kubernetes" talk at MOIA. More details about that once we solved the possible time conflict.

**Comment by roksolana-d** [comment]
Sure. Thanks you! I will follow the updates

**Comment by Jentsch** [comment]
Not an issue, #5 will take place in the second half of October.

**Comment by markusjura** [comment]
@roksolana-d We from MOIA are happy to host the meetup with your talk on 09.10.19. I could create a new event at meetup.com that you can then review. Let me know if this works for you.

**Comment by roksolana-d** [comment]
@markusjura that would be just great! It works for me

**Comment by markusjura** [comment]
@roksolana-d @Jentsch The event has been published at https://www.meetup.com/Scala-Berlin-Brandenburg/events/265090756. Closing the issue.

@roksolana-d Let me know via email if you need to more info/help for coming to our MOIA office. We will start preparing the event at 18:00. You are welcome to come to our office at that time or even earlier. Whatever suits you best :-)

**Comment by roksolana-d** [comment]
Sure, thanks again!
